### ISSUE TITLE
RealRTCW v4.0 bugs and suggestions for improvements

### ISSUE THREAD

**Issue by usergithub64** [wolfetplayer/RealRTCW#88] opened 2022-09-05 20:54 UTC
1. Wrong 16:9 aspect ratio in intro video and "Office Of Secret Actions" intro. Intro video and "Office Of Secret Actions" intro should be 16:9 as in RTCW v1.42d

True aspect 16:9 in RTCW v1.42d:
![WolfSP_2022_08_30_22_31_15_060](https://user-images.githubusercontent.com/58270614/188511968-0b41cc1a-54b5-42ba-9283-3f801a00cd18.png)

![unknownmap1](https://user-images.githubusercontent.com/58270614/188904178-7eb6ecef-0ace-4bdf-970b-8557c75e5259.jpg)

Wrong aspect 16:9 in RealRTCW v4.0:
![RealRTCW x64_2022_08_30_22_32_34_698](https://user-images.githubusercontent.com/58270614/188511978-36f8c712-be45-4860-98a0-5daa58904d33.png)

![unknownmap2](https://user-images.githubusercontent.com/58270614/188904193-1514da27-14b2-46df-a8f0-8a61f5fef066.jpg)

2. Sometimes the weapon freezes in the reload animation after loading a quick save until another key is pressed.

3. Sometimes when scrolling the mouse back or forward, the weapon is not selected from the available ones. For example, it is impossible to select pistols, rifles or grenades.

4. On the Crypt1 map, in the cut-scene where three soldiers are talking in the dungeon, the soldier holding the MG42 machine gun goes through the other soldiers due to the MG42 barrel being too long. Maybe it's better to put back the MP40 barrel that was in the original RTCW? Or you can replace the MP40 barrel with a STG44. The STG44 also has a normal barrel length. With STG44, the soldier does not pass through other soldiers when turning and does not hit them with the barrel of the STG44. How to fix: In the crypt1.ai file, on line 464, change "giveweaponfull weapon_mg42m" to "giveweaponfull weapon_mp44", on line 695, change "giveweaponfull weapon_mg42m" to "giveweaponfull weapon_mp44", on line 712, change "giveweaponfull weapon_mg42m" to "giveweaponfull weapon_mp44".

5. If you fire all six rounds from the shotgun, the shotgun will reload after loading the first round. It is not right. The shotgun should reload after loading the sixth round. Also need to fix manual reloading (after the number of rounds needed to fill the magazine is inserted into the shotgun, need to add the animation for reloading the shotgun pump action).

6. FG42 can't fire alternate fire while aiming. This is a bug. It needs to be fixed and the ability to shoot alternate fire in aiming mode should be added.

7. Too low rate of fire of FG42 in aiming mode compared to rate of fire in normal mode. The original RTCW does not have this bug (the FG42 has the same rate of fire in normal and aiming modes).

8. In OpenAL mode, the sound of the Flamethrower, Tesla is too loud. Also the sound of the fire when it sets the player on fire is too loud compared to other sounds. It is impossible to play at such a volume of a Flamethrower, Tesla and fire. It looks like OpenAL is buggy. You have to set seta s_useOpenAL to "0" to make Flamethrower, Tesla volume and fire volume the same compared to other sounds. Sound card Creative Sound Blaster X-Fi Titanium Fatal1ty Profess1onal. A bug needs to be fixed with OpenAL so that the volume of the Flamethrower, Tesla and igniting with fire is much quieter or the same compared to the rest of the sounds. How to fix (workaround): Reduce Flamethrower and fire sounds (fl_stream.wav, fl_start.wav, fl_fire.wav, fl_blow.wav, firecrack1.wav) by 30 dB in GoldWave Editor. Tesla sounds (zap1.wav, zap2.wav, zap3.wav) are reduced by 5 dB in the GoldWave Editor program. Tesla sound (loop.wav) is reduced by 15 dB in the GoldWave Editor program.

9. In the original RTCW, if you hold a chair in your hand, you can hit enemies with this chair. In RealRTCW, the chair does not hit when the button is pressed (only the sound of chair swinging is heard, there is no chair swinging animation). This bug appeared in ioRTCW after commit 069725d "All: Fix listen server sending snapshots each client frame" from Sep 19, 2017. How to fix: Need to revert this commit.

10. The shotgun model might be better replaced with a model from Medal Of Honor Allied Assault, because it looks much prettier, better and feels great when shooting and reloading, this is the best shotgun model with amazing reload animation ever created:
![MOHAA_2022_08_30_22_59_00_410](https://user-images.githubusercontent.com/58270614/188512077-50665930-082f-4565-981c-3bcdfa40eda9.png)

11. The STG44 reload sound precedes the reload animation (the magazine pull sound precedes the magazine pull animation).

12. On the Boss2 map, enemies appear from scratch after the gate rises all the way up. This bug only happens when installing Additional Enemies: More Enemies & Even More Enemies. It is necessary to correct the time of their appearance, that is, to make them appear immediately when loading the Boss2 map before raising the gate all the way up. How to fix: In the boss2.script file, in the "big_door1_lever" trigger section, on line 150 delete the line "wait 2000", on line 152 change the line "wait 11000" to "wait 1000".

13. On the Chateau map, when loading a quick save, an error message appears saying "Failed to load skin file: eliteguard\gretel". How to fix: In the file chateau.ents, on line 77, replace "eliteguard/gretel" with "eliteguard/chateau1", on line 167, replace "eliteguard/gretel" with "eliteguard/chateau1", on line 176, replace "eliteguard/gretel" with "eliteguard/chateau1".

14. "Third person view" & "Third person range" settings are not saved after exiting Windows and restarting the game.

15. There are no weapons in the Training level: grenade launcher, gas grenade, air strike flare grenade, Browning machine gun.

16. In the cut-scene of the "End" map, the image of Heinrich appears and twitches, rattles even before he crawls out of the ground. This bug only happens when installing Additional Enemies: Even More Enemies. With other Additional Enemies parameters, this bug is absent. It seems that this bug occurs due to too many additional enemies. How to fix: In the end.ai file, the section with additional enemies "#if g_reinforce" should be removed from the trigger section "playerstart" and added to the trigger section "fem1" "spawn" before "playanim get_up_still both forever". After this fix, the bug with Heinrich in the cut-scene is no longer there. Now you can add even more enemies to the "End" map.
>WolfETPlayer:  Applied

17. On the End map, after the last cut-scene with Blazkowicz, the main menu does not appear, and the game crashes to the Windows 10 desktop. This bug occurs on RealRTCW.x64.

18. When you turn on subtitles, they are located in the center of the screen and interfere with viewing cut-scenes. Subtitles must be moved to the bottom of the screen.

19. Grenade/dynamite throwing animation looks wrong. When throwing a grenade, the same hand with a grenade is visible (that is, a grenade is thrown by a hand already holding a grenade). It may be necessary to redo the animation so that the hand is empty after throwing a grenade.

20. The "Snooper" rifle model looks wretched and too bulky, covering half the screen. At the same time, the animation of reloading with pulling out the magazine and then inserting the magazine into the "Snooper" rifle is not visible. The model from the original RTCW was much better. Can you bring back the "Snooper" rifle model from the original RTCW or make it an optional mod?

21. The scope mode in the "Snooper" rifle, it would probably be better to replace it with the scope mode from the RTCW Venom mod v6.8U. There it is improved and refined. It looks much nicer in the color inversion in the night vision mode of this scope.

Sight mode in the "Snooper" rifle from the RealRTCW mod v4.0:
![RealRTCW x64_2022_09_06_17_43_40_115](https://user-images.githubusercontent.com/58270614/188665986-f1a01fd5-e910-48f6-a7c2-b444b1cb2b92.png)

Sight mode in the "Snooper" rifle from the RTCW Venom mod v6.8U:
![WolfSP_2022_09_06_17_44_59_544](https://user-images.githubusercontent.com/58270614/188666001-f878ea13-2fdc-42ba-bc03-36e1a646893e.png)

22. In main menu and after loading the map, there are a lot of error messages in the console about scripts, shaders, missing TGA files:

![RealRTCW x86_2022_09_05_18_13_42_977](https://user-images.githubusercontent.com/58270614/188661054-4d9d959a-ccbf-41f5-8476-a49bbc194923.png)

23. RealRTCW.x86 does not start or crashes to desktop if seta s_useOpenAL "0" is set. How to fix: You need to delete the file realrtcwconfig.cfg so that it will be created again the next time you start the game.

24. When picking up binoculars, there is no "Binoculars" message on the screen. How to fix: In the pickupnames.txt file, the "Binoculars" section must be set after the four "---" lines.

25. The Kar98k rifle has a muzzle flash above the barrel when fired. It is necessary to correct the muzzle flash and lower it lower.

26. In the first part of the "Trondheim Trilogy" add-on, when you start a new game, a cut-scene with a submarine starts and immediately skips, proceeding to the level loading. It is necessary to fix a bug with the cut-scene so that it plays to the end and does not skip automatically.

27. It is necessary to transfer the following fixes taken from the RTCW Venom mod v6.8U to RealRTCW:

1) Improved reaction and health of enemies.

2) Restored the missing line of the guard's conversation at the stairs and the greeting in the cut-scene on the Escape1 map. How to fix: In the escape1.ai file, add "playanim nazi_salute both" to the trigger section "trigger talk1" after line 481, and replace line 802 "wait 6000 nazi5" in the trigger section "trigger getgoing2" with:
wait 2500 Nazi5
playsound Esc1Nazi2_5
wait 3500 Nazi5

3) Fixed the action of a soldier on the bridge in the base, now he correctly launches a grenade before firing from a machine gun.

4) Zombies now try to quickly get close to the player at any cost.

5) Little changes in some cut-scenes.

6) Fixed script to avoid lag in Norway level.

7) Bosses are now 2 times stronger than default.

8) The greeting in the cut-scene of the conversation with the "Death's Head" on the submarine has been restored. How to fix: In the swf.ai file, in the "trigger mtalk2" trigger section, delete line 405 "accum 0 abort_if_not_bitset 0", after line 406 "playsound SWFmajor_2" add the line "playanim nazi_salute both".

28. The Luger pistol model has the wrong animation. At the time of the shot, there is no open shutter of the pistol. Also, when reloading after pulling out the magazine, the pistol bolt must be open and then closed when the magazine is inserted into the pistol. For comparison, you can watch the animation of the Luger pistol in the original RTCW in slow motion. There is no such bug in the original RTCW with Luger pistol animation.

29. In third person mode, when using a stationary MG42, its model passes through the player:
![RealRTCW x64_2022_09_10_12_12_08_495](https://user-images.githubusercontent.com/58270614/189477655-8b928a9e-f936-47e4-8fb1-93b45d17428a.png)
![RealRTCW x64_2022_09_10_12_12_39_922](https://user-images.githubusercontent.com/58270614/189477988-d6dba7f0-0648-431e-97d9-76aa35fdbb13.png)
![RealRTCW x64_2022_09_10_12_12_36_201](https://user-images.githubusercontent.com/58270614/189477992-d2557cef-dde1-4fd3-9b1c-68993b0d6196.png)

30. In third person, the knife model does not look right:
![RealRTCW x64_2022_09_10_11_45_50_758](https://user-images.githubusercontent.com/58270614/189477668-f62069cb-3500-4580-a287-cf1861242723.png)

31. In third person mode, the model of the Browning machine gun does not look right:
![RealRTCW x64_2022_09_10_11_50_20_774](https://user-images.githubusercontent.com/58270614/189477673-1934347a-260a-4552-a8ef-8e32c03453d9.png)

32. In QUAKE/DOOM and COD1/MOHAA weapon mode, the Browning machine gun model is incorrectly positioned on the screen (the model is too far from the screen, so the arm seems too long, and when changing weapons or in reload mode, the arm is cut off):
![RealRTCW x64_2022_09_10_11_44_08_634](https://user-images.githubusercontent.com/58270614/189477697-62ed161c-7ae9-412a-a7f7-2ab5e26add40.png)
![RealRTCW x64_2022_09_10_11_42_09_967](https://user-images.githubusercontent.com/58270614/189477709-081d6483-6f0a-495a-9a6a-83e3df53b2e1.png)
![RealRTCW x64_2022_09_10_11_44_37_725](https://user-images.githubusercontent.com/58270614/189477727-dd56dd21-9b1e-4704-860f-a00c413ece58.png)
![RealRTCW x64_2022_09_10_11_41_41_092](https://user-images.githubusercontent.com/58270614/189477741-c055d993-8af5-42d8-9787-9068ef0f06ac.png)

33. In COD1/MOHAA weapon mode, when reloading PPSH41, its model is cut off/goes off screen (it seems that the PPSH41 model is too close to the player's view):
![RealRTCW x64_2022_09_10_11_39_33_284](https://user-images.githubusercontent.com/58270614/189477752-19676cab-1efe-441f-8685-2fbba7ef0524.png)

34. When setting the transparency of the HUD to the minimum value, the icons of health, stamina, items, weapons still remain opaque:
![RealRTCW x64_2022_09_10_11_30_16_929](https://user-images.githubusercontent.com/58270614/189478302-b476e0f9-52c4-4314-9a6e-eb1fd0aef735.png)

35. The transparency of the sight does not change when changing the slider for adjusting the transparency of the sight, the sight still remains opaque.

36. If you press "Win + D" while loading a level, sometimes the game may freeze with an error message.

37. If you do not skip cut-scenes when starting a new game, then additional enemies will not appear on the Escape1 map. The "Even More Enemies" option is set and the "Bring'em on!" difficulty is selected. If you skip cut scenes when starting a new game, then additional enemies will appear on the Escape1 map. Checked at the very beginning, when the player picks up the knife, there is a long corridor, then there is one additional enemy around the left corner, and there is one additional enemy around the right corner. Perhaps this bug is present on other maps, in front of which there is a cut-scene. How to fix: In the escape1.ai file, the section with additional enemies "#if g_reinforce" should be removed from the trigger section "trigger camerainterrupt" "trigger dummy cine1_cleanup" and added to the trigger section "trigger fix_bitset0" after the trigger section "selectweapon weapon_knife". After this fix, additional enemies will spawn if cutscenes are not skipped.

38. When the "Show Weapon Icon" option is disabled, if you hold the throw button before throwing a grenade/dynamite to decrease/increase the timer until the explosion, then the sound of the timer is not heard. That is, grenpulse1.wav, grenpulse2.wav, grenpulse3.wav, grenpulse4.wav files are not played. Need to fix this bug.

39. The w3d_sec map is missing a table texture. That is, the file table_round.jpg is missing along the path: \models\objects\Prague\furniture\. How to fix: Take the table_round.jpg file from the separately downloaded w3d_sec map.
>WolfETPlayer:  Applied

40. On the w3d and w3d_sec maps, there is no option to enable the Additional Enemies: More Enemies & Even More Enemies option. That is, with the Additional Enemies: More Enemies & Even More Enemies option enabled, additional enemies do not appear on these maps. This bug needs to be fixed. 
> WolfETPlayer: It's not a bug. I have no intention to add additional enemies to those levels.

41. Cursor not showing in RealRTCW console. This is inconvenient, because when editing already entered commands, it is impossible to determine under which character the cursor is located in order to replace the erroneously entered character. In the original RTCW, the cursor is displayed normally. How to fix: Take the bigchars.tga file from the z_zrealrtcw_localization_rus.pk3 archive or from the original archive pak0.pk3 and replace the corresponding file along the \gfx\2d\ path in the z_realrtcw_localization.pk3 archive.

42. The Dog Idle animation only plays once. That is, the animation of the inactivity of the dog loops. How to fix: You need to fix the \models\players\dog\wolfanim.cfg file. At idle, the looping frames were 0. You need to copy the length value "501" into the looping frames and the animation will work fine.
>WolfETPlayer:  Applied

44. If you set "Third person view" and then load a quick save, the view will reset to first person view. That is, the "Third person view" setting is not retained after a quick save is loaded.

45. Is it possible to return the HUD back, as in RealRTCW v3.3? And most importantly, return the position of messages about pickups on the left as in RealRTCW v3.3 ? Please make it an optional mod or tell us what needs to be fixed in the game resources or config files.
>WolfETPlayer:  There is already option for vanilla like HUD. Pickup position message will stay centered.

46. The Femzombie model has a transparent body, meaning it looks empty and see through. How to fix: In the z_zzrealrtcw_scripts.pk3 archive, along the path \scripts\ in the models.shader file, the lines of the shader "models/players/femzombie/wt_body1" are missing. They can be taken from a similar file in the original RTCW.
>WolfETPlayer:  Applied

47. The option added (restored as a patch) to the menu to assign a key to create screenshots does not work. In the original RTCW, this option works fine. Possibly a bug in the RealRTCW engine. How to fix: Add the following lines to the \code\ui\ui_shared.c file after line 3730:
{"screenshot", -1, -1, -1, -1}, //For screenshot TGA
{"screenshotjpeg", -1, -1, -1, -1} //For screenshot JPEG

Now you can add options to the menu to configure the keys for saving screenshots (For example, F11 and F12), and they will be saved in the realrtcwconfig.cfg file.

48. Escape1 and many other maps do not have moving clouds in the sky. There is also no moon in the sky. The original RTCW does not have these bugs. How to fix: Take the gfx.shader and sky.shader files from the original RTCW.

49. When launching the map with the "\spdevmap" parameter and then using the "\give" parameter in the console, the following weapons cannot be obtained: luger_silenced, mauser, sniperrifle, fg42, ithaca, tesla, airstrike, poisongas. For example, when using the "\give luger_silenced" parameter in the console, this weapon is not issued. The rest of the weapon through the "\give" parameter is issued normally. 
>WolfETPlayer: You are using wrong weapon code names. For example ithaca is coded in as m97. The rest could be looked up in the code.

**Comment by wolfetplayer** [comment] 2022-09-07 09:58
Oof. Im yet read it. But thanks for compiling it all together.

**Comment by maximus105** [comment] 2022-09-09 14:37
I've updated most of the bugs (rephrased and corrected the bug descriptions) in the list and added new ones. If some bugs are fixed, can you tell me or tell me where to download the patches with fixes so that I can test them? Are there any other questions:
1. Is it possible to run RealRTCW add-ons from the command line immediately, like the "+set game" command, as in Quake 2?
2. RealRTCW v4.0 uses the original knife model. Where can I get an updated knife model, as in this video
https://youtu.be/sbu0wan9NKI

**Comment by maximus105** [comment] 2022-09-09 16:11
The Luger pistol has the wrong animation. At the time of the shot, there is no open shutter of the pistol. Also, when reloading after pulling out the magazine, the pistol bolt must be open and then closed when the magazine is inserted into the pistol. For comparison, you can watch the animation of the Luger pistol in the original RTCW in slow motion. There is no such bug in the original RTCW with Luger pistol animation.

**Comment by maximus105** [comment] 2022-09-10 09:53
29. In third person mode, when using a stationary MG42, its model passes through the player:
![RealRTCW x64_2022_09_10_12_12_08_495](https://user-images.githubusercontent.com/58270614/189477655-8b928a9e-f936-47e4-8fb1-93b45d17428a.png)
![RealRTCW x64_2022_09_10_12_12_39_922](https://user-images.githubusercontent.com/58270614/189477988-d6dba7f0-0648-431e-97d9-76aa35fdbb13.png)
![RealRTCW x64_2022_09_10_12_12_36_201](https://user-images.githubusercontent.com/58270614/189477992-d2557cef-dde1-4fd3-9b1c-68993b0d6196.png)

30. In third person, the knife model does not look right:
![RealRTCW x64_2022_09_10_11_45_50_758](https://user-images.githubusercontent.com/58270614/189477668-f62069cb-3500-4580-a287-cf1861242723.png)

31. In third person mode, the model of the Browning machine gun does not look right:
![RealRTCW x64_2022_09_10_11_50_20_774](https://user-images.githubusercontent.com/58270614/189477673-1934347a-260a-4552-a8ef-8e32c03453d9.png)

32. In QUAKE/DOOM and COD1/MOHAA weapon mode, the Browning machine gun model is incorrectly positioned on the screen (the model is too far from the screen, so the arm seems too long, and when changing weapons or in reload mode, the arm is cut off):
![RealRTCW x64_2022_09_10_11_44_08_634](https://user-images.githubusercontent.com/58270614/189477697-62ed161c-7ae9-412a-a7f7-2ab5e26add40.png)
![RealRTCW x64_2022_09_10_11_42_09_967](https://user-images.githubusercontent.com/58270614/189477709-081d6483-6f0a-495a-9a6a-83e3df53b2e1.png)
![RealRTCW x64_2022_09_10_11_44_37_725](https://user-images.githubusercontent.com/58270614/189477727-dd56dd21-9b1e-4704-860f-a00c413ece58.png)
![RealRTCW x64_2022_09_10_11_41_41_092](https://user-images.githubusercontent.com/58270614/189477741-c055d993-8af5-42d8-9787-9068ef0f06ac.png)

33. In COD1/MOHAA weapon mode, when reloading PPSH41, its model goes off screen (it seems that the PPSH41 model is too close to the player's view):
![RealRTCW x64_2022_09_10_11_39_33_284](https://user-images.githubusercontent.com/58270614/189477752-19676cab-1efe-441f-8685-2fbba7ef0524.png)

34. When setting the transparency of the HUD to the minimum value, the icons of health, stamina, items, weapons still remain opaque.
35. The transparency of the sight does not change when changing the slider for adjusting the transparency of the sight, the sight still remains opaque.
36. If you press "Win + D" while loading a level, sometimes the game may freeze with an error message.

**Comment by maximus105** [comment] 2022-09-13 17:25
38. When the "Show Weapon Icon" option is disabled, if you hold the throw button before throwing a grenade/dynamite to decrease/increase the timer until the explosion, then the sound of the timer is not heard. That is, grenpulse1.wav, grenpulse2.wav, grenpulse3.wav, grenpulse4.wav files are not played.

**Comment by maximus105** [comment] 2022-09-24 06:10
39. The w3d_sec map is missing a table texture. That is, the file table_round.jpg is missing along the path \models\objects\Prague\furniture\

Screenshot from w3d_sec map in RealRTCW:
![shot0001](https://user-images.githubusercontent.com/58270614/192082816-98f94cb3-d909-4d04-a882-c11613b5d897.jpg)

Screenshot from a separately downloaded w3d_sec map:
![shot0000](https://user-images.githubusercontent.com/58270614/192082819-67297952-915f-4143-8de8-ece573c02a14.jpg)

40. On the w3d and w3d_sec maps, there is no option to enable the Additional Enemies: More Enemies & Even More Enemies option. That is, with the Additional Enemies: More Enemies & Even More Enemies option enabled, additional enemies do not appear on these maps. This bug needs to be fixed.

**Comment by KuehnhammerTobias** [comment] 2022-09-26 16:16
@maximus105 
Hi! It really deserves a lot of credit for how accurate and dedicated you are to finding bugs.
It is very helpful to get feedback for such a great product, like RealRTCW. I'm not part of the RealRTCW team, but I'm very interested in the project. I also follow the various bugs that are reported. Hence my question: 
Could you imagine dividing all of the issues/bugs you found into individual tickets?
Normally it is standard to generate a ticket per issue. This makes it easier for developers to fix the individual errors.
Especially since some bugs are very easy to fix, while other bugs require a lot of programming work. For example how should someone report that one issue is solved. How will you manage that with such a report? Btw, you can at least have some task lists. This makes it at least possible to see wich issues are solved. Have a look at how to write task lists on Github: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#task-lists
Second, not every problem needs so many level shots, this error report sometimes takes a long time to load just because of that many screenshots.
Well, I hope I wasn't too offensive, I really like your report.
Thank you!

**Comment by maximus105** [comment] 2022-09-26 17:10
> I have not yet figured out how to separate all the problems / errors found into separate tickets.

**Comment by wolfetplayer** [comment] 2022-09-26 17:15
Keep it as it is.

**Comment by maximus105** [comment] 2022-09-26 17:16
41. Cursor not showing in RealRTCW console. This is inconvenient, because when editing already entered commands, it is impossible to determine under which character the cursor is located in order to replace the erroneously entered character. In the original RTCW, the cursor is displayed normally.

**Comment by KuehnhammerTobias** [comment] 2022-09-26 18:02
Okay, currently I'm working on an OpenAL overhaul (for idtech3), so probably I can help with 8 (if help is wanted). What OpenAL version is used? It really makes me wonder that this is the only(?) difference that occurs for you, concerning SDL/OpenAL differences.

**Comment by maximus105** [comment] 2022-09-27 13:56
Windows 10 Pro x64 v21H2 has OpenAL v2.1.0.0 installed. The RealRTCW folder contains the files OpenAL32.dll v1.21.1 and OpenAL64.dll v1.21.1

**Comment by maximus105** [comment] 2022-09-28 16:18
When starting RealRTCW x86, the following is displayed in the console:
![RealRTCW x86](https://user-images.githubusercontent.com/58270614/192832093-1b44272d-179f-403f-99d3-66633ffd05de.png)

When starting RealRTCW x64, the following is displayed in the console:
![RealRTCW x64](https://user-images.githubusercontent.com/58270614/192832130-40fe52d3-e339-43ad-9fcd-4fb386def575.png)

**Comment by maximus105** [comment] 2022-10-04 04:44
43. If you set "Third person view" and then load a quick save, the view will reset to first person view. That is, the "Third person view" setting is not retained after a quick save is loaded.

**Comment by maximus105** [comment] 2022-10-18 06:56
44. Is it possible to return the HUD back, as in RealRTCW v3.3? And most importantly, return the position of messages about pickups on the left as in RealRTCW v3.3 ? Please make it an optional mod or tell us what needs to be fixed in the game resources or config files.

**Comment by maximus105** [comment] 2022-10-22 09:38
45. The Femzombie model has a transparent body, meaning it looks empty and see through. How to fix: In the z_zzrealrtcw_scripts.pk3 archive along the \scripts\ path in the models.shader file, the shader line "models/players/femzombie/wt_body1" is missing. They can be taken from a similar file in the original RTCW.

**Comment by maximus105** [comment] 2022-10-25 07:48
I added to some bug descriptions a description of their fix. I tested these fixes as a patch created as a .pk3 archive

**Comment by maximus105** [comment] 2022-11-05 07:51
Regarding bug #9: RealRTCW v2.2 doesn't have this bug yet. That is, the animation of hitting the chair works properly. And in RealRTCW v3.3 there is no animation of hitting a chair anymore. It seems to be related to wolfanim.cfg and wolfanim.script files for player. Or the bug is related to the RealRTCW engine.

**Comment by maximus105** [comment] 2022-12-18 12:27
47. Escape1 and many other maps do not have moving clouds in the sky. There is also no moon in the sky. The original RTCW does not have these bugs. How to fix: Take the gfx.shader and sun.shader files from the original RTCW.

**Comment by maximus105** [comment] 2023-01-04 21:44
@wolfetplayer Can you help me figure out how to fix bug №9? I tried to take the wolfanim.cfg and wolfanim.script files for the BJ player from the original RTCW and replace the corresponding files in RealRTCW with them, but the chair swing animation did not appear. Maybe it's a bug in the RealRTCW v4.0 engine? RealRTCW v2.2 doesn't have this bug yet.

**Comment by wolfetplayer** [comment] 2023-01-04 22:13
Code is the same. Issue is probably in chair02.mdc (models/furniture). But not sure.

**Comment by maximus105** [comment] 2023-01-07 20:17
48. When launching the map with the "\spdevmap" parameter and then using the "\give" parameter in the console, the following weapons cannot be obtained: luger_silenced, mauser, sniperrifle, fg42, ithaca, tesla, airstrike, poisongas. For example, when using the "\give luger_silenced" parameter in the console, this weapon is not issued. The rest of the weapon through the "\give" parameter is issued normally.

**Comment by maximus105** [comment] 2023-01-20 13:30
@wolfetplayer After update v4.0.10 bug №14 was fixed, but bug №43 was not fixed. That is, if you set "Third Person View", save the game, and then load a save or quick save, the view will reset to first person view. That is, the "Third Person View" setting is not retained after a quick save is loaded. A quick throw of a grenade looks very strange, that is, a grenade is thrown by an outsider from the air, while the player's hands are already holding the weapon. Are there any plans to improve the quick throw grenade animation? That is, make the animation so that when a quick grenade is thrown, the current weapon is first removed, the grenade throw animation appears, and then the current weapon that was selected before the quick grenade throw appears.

**Comment by maximus105** [comment] 2023-02-14 09:48
@wolfetplayer Is it possible to undo the "centered pickup string" commit, and make the pickup string on the left, as it was in the original? Is it possible to make this setting configurable through the main menu of the game or release it as a separate mod? Could you please tell me how to compile engine files with this undone commit via github?

**Comment by maximus105** [comment] 2023-02-24 17:38
I found out the cause of bug №9. This bug is also present in the ioRTCW engine after commit 069725d "All: Fix listen server sending snapshots each client frame" from Sep 19, 2017. After reverting this commit, the chair swing animation works fine. I also reported this bug to the ioRTCW repository.

**Comment by wolfetplayer** [comment] 2023-02-25 13:39
> I found out the cause of bug №9. This bug is also present in the ioRTCW engine after commit 069725d "All: Fix listen server sending snapshots each client frame" from Sep 19, 2017. After reverting this commit, the chair swing animation works fine. I also reported this bug to the ioRTCW repository.

Thanks, I take a look.

**Comment by maximus105** [comment] 2023-02-26 07:57
49. Cvar "cg_crosshairHealth" does not work in RealRTCW. When "cg_crosshairHealth 1" is set, the color of the sight still does not change with decreasing/increasing health and always remains white. In ioRTCW cvar "cg_crosshairHealth" works fine. This may be due to ioRTCW commit 692a487 "MP: Fix cg_crosshairHealth" from May 9, 2016, which is not used for RealRTCW.

**Comment by wolfetplayer** [comment] 2023-02-26 20:46
I remember commenting this one out due to max cap differences on various difficulty levels. Gonna redo it.

**Comment by maximus105** [comment] 2023-03-12 08:38
I found out the cause of bug №46. Add the following lines to the \code\ui\ui_shared.c file after line 3730:
{"screenshot", -1, -1, -1, -1},   //For screenshot TGA
{"screenshotjpeg", -1, -1, -1, -1}   //For screenshot JPEG

Now you can add options to the menu to configure the keys for saving screenshots (For example, F11 and F12), and they will be saved in the realrtcwconfig.cfg file.

**Closed** 2024-06-15 07:41 UTC
